version: '3.1'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: db1usr
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_wp_password 
      WORDPRESS_DB_NAME: wpdb167
    depends_on:
      - db
    secrets:
      - db_wp_password
    networks:
      mysql_internal:
        aliases: ["db"]
      wordpress_public:
#    volumes:
#      - themes:/var/www/html/wp-content/themes
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password 
      MYSQL_DATABASE: wpdb167
      MYSQL_USER: db1usr
      MYSQL_PASSWORD_FILE: /run/secrets/db_wp_password
    networks:
      mysql_internal:
        aliases: ["wordpress"]
    secrets:
      - db_root_password
      - db_wp_password 

  watchtower:
    image: v2tec/watchtower
    restart: always
    depends_on:
      - wordpress
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mysql_internal:
      wordpress_public:

secrets:
  db_root_password:
    file: secrets/db_root_password.txt
  db_wp_password:
    file: secrets/db_wp_password.txt

networks:
  mysql_internal:
    driver: "overlay"
    internal: true
  wordpress_public:
    driver: "overlay"
volumes:
  db_data: {}
#  themes: {}
